"use client";

import PlaySection from "@/fe/components/feature/Play/PlaySection";
import { useParams } from "next/navigation";

export default function PlayQuizPage() {
  const { quizId } = useParams();

  return (
    <div className="h-full w-full flex items-center justify-center flex-col gap-5">
      <PlaySection />
      <div>
        Generated by <span className="text-primary font-bold">Memento</span>
      </div>
    </div>
  );
}
