export const ALPHABET_OPTIONS = [
	{ value: "A", index: 0 },
	{ value: "B", index: 1 },
	{ value: "C", index: 2 },
	{ value: "D", index: 3 },
	{ value: "E", index: 4 },
	{ value: "F", index: 5 },
	{ value: "G", index: 6 },
	{ value: "H", index: 7 },
	{ value: "I", index: 8 },
	{ value: "J", index: 9 },
	{ value: "K", index: 10 },
	{ value: "L", index: 11 },
	{ value: "M", index: 12 },
	{ value: "N", index: 13 },
	{ value: "O", index: 14 },
	{ value: "P", index: 15 },
	{ value: "Q", index: 16 },
	{ value: "R", index: 17 },
	{ value: "S", index: 18 },
	{ value: "T", index: 19 },
	{ value: "U", index: 20 },
	{ value: "V", index: 21 },
	{ value: "W", index: 22 },
	{ value: "X", index: 23 },
	{ value: "Y", index: 24 },
	{ value: "Z", index: 25 },
] as const;
